export const listOptionsSideBar=[
    {
        label:"Getting started",
        icon:undefined,
        onClick:undefined
    },
    {
        label:"Components",
        icon:undefined,
        onClick:undefined
    },
    {
        label:"Documentation",
        icon:undefined,
        onClick:undefined,
        subMenu:[
            {
                label:"Dropzone",
                icon:undefined,
                onClick:undefined
            },
            {
                label:"FileMosaic",
                icon:undefined,
                onClick:undefined
            },
            {
                label:"Dropzone",
                icon:undefined,
                onClick:undefined
            },
        ]
    },
];